# Borrowed from https://github.com/sfackler/rust-postgres/blob/04bd98e7edb238511661b311c725a176012bca6a/.circleci/config.yml
# Used under MIT license.

restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
restore_deps: &RESTORE_DEPS
  restore_cache:
    keys:
      - deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
      - deps-{{ checksum "~/rust-version" }}-
save_deps: &SAVE_DEPS
  save_cache:
    key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
    paths:
    - target
    - /usr/local/cargo/registry/cache

version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1-browsers
        environment:
          RUSTFLAGS: -D warnings
          POSTGRES_URL: "postgres://circleci@localhost:5432/circleci-rustbucks"

      - image: postgres:11.2-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circleci-rustbucks

    steps:
      - checkout
      - *RESTORE_REGISTRY
      - run: cargo generate-lockfile
      - *SAVE_REGISTRY
      - run: rustc --version | tee ~/rust-version
      - *RESTORE_DEPS
      - run: cargo build --all --tests --locked
      - *SAVE_DEPS
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: env RUST_BACKTRACE=1 cargo test -p rustbucks --locked
