[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "rustbucks"
version = "0.1.0"
edition = "2018"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.7"
env_logger = "0.6.2"
envy = "0.4.0"
failure = "0.1.3"
futures = "0.1.29"
hex-slice = "0.1.4"
hyper = "0.12.35"
log = "0.4.8"
maplit = "1.0.2"
r2d2 = "0.8.5"
r2d2_postgres = "0.14.0"
rand = "0.7.1"
serde = {version="1.0.101", features=["derive"]}
serde_json = "1.0.40"
structopt = "0.3.1"
tokio = "0.1.22"
toml = "0.5.3"
url = "2.1.0"
time = "0.1.42"
actix-service = "0.4.2"
actix-http-test = "0.2.4"
actix-http = "0.2.8"
actix-threadpool = "0.1.2"
jemallocator-global = "0.3.2"
actix-files = "0.1.4"
infra = { path = "../infra" }

[dependencies.weft]
git = "https://github.com/cstorey/weft.git"

[dependencies.weft_derive]
git = "https://github.com/cstorey/weft.git"
optional = false

[dependencies.weft-actix]
git = "https://github.com/cstorey/weft.git"

[dev-dependencies]
serde_json = "1.0.40"
lazy_static = "1.4.0"

[dev-dependencies.sulfur]
git = "https://github.com/cstorey/sulfur.git"
optional = false
