[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "rustbucks"
version = "0.1.0"

[dependencies]
base64 = "0.10.0"
byteorder = "1.2.7"
failure = "0.1.3"
futures = "0.1.25"
hyper = "0.12.13"
lazy_static = "1.1.0"
log = "0.4.5"
pretty_env_logger = "0.2.4"
serde = "1.0.80"
serde_derive = "1.0.80"
siphasher = "0.2.3"
tokio = "0.1.11"
tokio-threadpool = "0.1.9"
url = "1.7.1"
warp = "0.1.7"

[dependencies.weft]
git = "https://github.com/cstorey/weft.git"
optional = false

[dependencies.weft_derive]
git = "https://github.com/cstorey/weft.git"
optional = false

[dev-dependencies]

[dev-dependencies.sulfur]
git = "https://github.com/cstorey/sulfur.git"
optional = false
