[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "rustbucks"
version = "0.1.0"

[dependencies]
actix = "0.8.3"
actix-web = "1.0.3"
base64 = "0.10.0"
env_logger = "0.6.2"
envy = "0.4.0"
failure = "0.1.3"
futures = "0.1.28"
hex-slice = "0.1.4"
hyper = "0.12.32"
lazy_static = "1.3.0"
log = "0.4.7"
maplit = "1.0.1"
r2d2 = "0.8.5"
r2d2_postgres = "0.14.0"
rand = "0.7.0"
serde = "1.0.94"
serde_derive = "1.0.94"
serde_json = "1.0.40"
siphasher = "0.3.0"
structopt = "0.2.18"
tokio = "0.1.22"
toml = "0.5.0"
url = "1.7.1"
hybrid-clocks = { git = "https://github.com/cstorey/hybrid-clocks.git" }
time = "0.1.42"
rustbucks-vlq = { path = "../vlq" }
actix-service = "0.4.1"
actix-http-test = "0.2.3"
actix-http = "0.2.5"
actix-threadpool = "0.1.1"
jemallocator-global = "0.3.2"
actix-files = "0.1.3"

[dependencies.postgres]
features = ["with-serde_json"]
version = "0.15.2"

[dependencies.weft]
git = "https://github.com/cstorey/weft.git"
optional = false

[dependencies.weft_derive]
git = "https://github.com/cstorey/weft.git"
optional = false

[dev-dependencies]
serde_json = "1.0.40"

[dev-dependencies.sulfur]
git = "https://github.com/cstorey/sulfur.git"
optional = false
