[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "rustbucks"
version = "0.1.0"

[dependencies]
failure = "0.1.3"
hyper = "0.12.13"
lazy_static = "1.1.0"
log = "0.4.5"
pretty_env_logger = "0.2.4"
serde = "1.0.80"
serde_derive = "1.0.80"
url = "1.7.1"
warp = "0.1.7"

[dev-dependencies.sulfur]
optional = false
path = "../sulfur"

[dependencies.weft]
git = "https://github.com/cstorey/weft.git"
optional = false

[dependencies.weft_derive]
git = "https://github.com/cstorey/weft.git"
optional = false
